SELECT ROW_NUMBER() OVER(PARTITION BY E1.INDV_ISCD
        ORDER BY E1.UNAS_ISCD) AS RNUM,
       INDV_ISCD,
       UNAS_INTL_PRC,
       BARR_VAL, --기초자산별 KI barrier
       BARR_HIT_CLS_CODE,  --기초자산별 KI Hit flag
       DECODE(E1.UNAS_ISCD,'NIKKEI225','NKY',E1.UNAS_ISCD) UNAS_ISCD,
       KOR_ISSU_ABWR_NAME
FROM   BSYS.TBSIMO202D00@GDW E1,
       BSYS.TBSIMM100M00@GDW E2
WHERE  E1.UNAS_ISCD = E2.STND_ISCD
AND E1.INDV_ISCD = :indv_iscd