SELECT FD.PROD_FNCD,
       ID.INDV_ISCD,
       FD.PROD_CLS_CODE,
       FD2.PROD_CLS_CODE PROD_CLS_CODE_D, --2024.07.16 대상 ELB 구분 목적(deal_ticket.floor=1)
       ID.CLRD_TYPE_CODE,
       FD.STLM_CRCD,
       ID.DEAL_CLS_CODE,
       FD.REAL_PBLC_FCAM,
       FD.PBLC_STCK_QTY,
       nvl(QT.RMND_QTY,0) RMND_QTY,
       FD.FUND_PBLC_UNPR,
       ID.PERC_APLY_THPR,
       TO_CHAR(TO_DATE(NVL(FD.FRST_STND_PRC_FIN_DATE,ID.PBLC_DATE), 'YYYYMMDD'), 'YYYY-MM-DD') FRST_STND_PRC_FIN_DATE, --최초기준가결정일 없을 경우, 발행일로 강제 대체
       TO_CHAR(TO_DATE(ID.PBLC_DATE, 'YYYYMMDD'), 'YYYY-MM-DD') PBLC_DATE,
       TO_CHAR(TO_DATE(ID.MTRT_DATE, 'YYYYMMDD'), 'YYYY-MM-DD') MTRT_DATE,
       ID.UNAS_CHOC_MTHD_CODE,
       ID.BARR_EN,
       ID.BARR_VAL1,
       ID.BARR_HIT_CLS_CODE,
       ID.BARR_HIT_DATE, 
       ID.MNTG_CYCL_CODE,
       ID.MNTG_STA_DATE,
       ID.MNTG_CLSN_DATE
FROM   BSYS.TBSIMO100M00@GDW FD,
       BSYS.TBSIMO100M00@GDW FD2, --v
       BSYS.TBSIMO201M00@GDW ID,
       BSYS.TBSIMO201M00@GDW ID2, --v
       BSYS.TBFNOM021L00@GDW QT
WHERE  ID.INDV_ISCD = :indv_iscd
AND    ID.OTC_FUND_ISCD = FD.OTC_FUND_ISCD
AND    ID.HEDG_ISCD = DECODE(FD.HEDG_TR_TYPE_CODE,'1',ID2.HEDG_ISCD,ID2.INDV_ISCD) --2024.07.16 자체/백투백 구분에 따라 조건 변경
AND    ID2.OTC_FUND_ISCD = FD2.OTC_FUND_ISCD --v
--AND    ID2.OTC_FUND_ISCD <> FD.OTC_FUND_ISCD --v
AND    ID2.OTC_FUND_ISCD <> DECODE(FD.PROD_FNCD,'SF003','NULL',FD.OTC_FUND_ISCD) --2024.07.16 자체/백투백 구분에 따라 조건 변경
AND    QT.ISCD(+) = ID.INDV_ISCD
AND    QT.STND_DATE(+) = :tdate 