SELECT SRNO,
       SDPR_LOEQ_RATE,
       SDPR_EXCS_RATE,
       INVL_RATE,
       MTRT_ERT
FROM   BSYS.TBSIMO205D00@GDW
WHERE  INDV_ISCD = :indv_iscd
AND    BARR_HIT_YN = 'N'
AND    SDPR_LOEQ_RATE <> SDPR_EXCS_RATE
ORDER BY SDPR_LOEQ_RATE, SDPR_EXCS_RATE