SELECT B.SRNO,
       to_date(B.TRTH_CLRD_DTRM_DATE,'YYYYMMDD') TRTH_CLRD_DTRM_DATE,
       B.UNAS_SDRT1,
       B.CLRD_ERT,
       nvl(B.AVRG_APLY_YN,'N') AVRG_APLY_YN,
       nvl(S.STRIKE_SMOOTHING_WIDTH,0) STRIKE_SMOOTHING_WIDTH,
       nvl(S.PERFORMANCE_TYPE,-1) PERFORMANCE_TYPE
FROM   (SELECT ROW_NUMBER() OVER (ORDER BY CALL_DATE) RNUM,
               ASSET_CODE,
               STRIKE_SMOOTHING_WIDTH,
               PERFORMANCE_TYPE
        FROM   SPS.AC_SCHEDULE
        WHERE  ASSET_CODE=:INDV_ISCD) S,
       (SELECT INDV_ISCD, SRNO, TRTH_CLRD_DTRM_DATE, UNAS_SDRT1, CLRD_ERT, AVRG_APLY_YN FROM BSYS.TBSIMO203D00@GDW WHERE INDV_ISCD=:INDV_ISCD) B
WHERE  S.ASSET_CODE(+)=B.INDV_ISCD
AND    S.RNUM(+) = B.SRNO
ORDER BY TRTH_CLRD_DTRM_DATE