SELECT RCVN_CLS_CODE,
       PRVS_DATE,
       INT_AMT,
       INDT_MNRT_ADJS_DATE,
       A.CCLS_MNRT,
       B.PRVS_ADTN_MNRT,
       VLTN_STA_DATE,
       VLTN_FIN_DATE,
       CRCD
FROM   BSYS.TBSIMO216L00@GDW A,
       BSYS.TBSIMO201M00@GDW B
WHERE  A.INDV_ISCD = B.INDV_ISCD
AND    A.INDV_ISCD = :indv_iscd
AND    RCVN_CLS_CODE = '2'