Option Explicit


Public trade_number As Integer
Public asset_code As String
Public fund_code As String
Public trade_date As Date
Public trade_price As Double
Public qty As Double
Public broker As String
Public LIVE_YN As String
Public CONFIRM_YN As String

Public product_code As String
Public bl_code As String
Public ul_code As String
Public strike As Double
Public option_type As String
Public exercise_style As String
Public last_trade_date As Date
Public lot_size As Double
Public flag As Integer

Public crncy As String